### ISSUE TITLE
Test/Review: Update centering of coordinates

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/DSSM#196]
- [ ] Center planar coordinates at 180 degrees instead of 160 degrees. 
- [x] Do transposition approach so that estimates in the Atlantic and Pacific areas are the same.

**Comment by arunge** [comment]
@isomemo As discussed, I added the option to center coordinates before modeling starts to _Atlantic_ or _Pacific_ with [version 24.05.1](https://github.com/Pandora-IsoMemo/iso-app/pull/215) on [iso-app beta](https://isomemoapp.com/app/iso-memo-app-beta). A detailed description can be found [here](https://github.com/Pandora-IsoMemo/iso-app/pull/215#issue-2282617179).

After you have checked the new feature, please, let us decide how to continue with the point:
> Center planar coordinates at 180 degrees instead of 160 degrees.

**Comment by isomemo** [comment]
@arunge There are differences in notation in left and right side of interface inputs (one mentions 180 and the other 160). Also the centering of a map is not really being made at either 160 or 180. See figure below.
![image](https://github.com/user-attachments/assets/495cfe68-8677-49c3-8e96-d32e5509b155)
