### ISSUE TITLE
[MPI_erweiterung_PRIORITY_007]: Pandora/isomemo - Batch export options for all different models mapping models

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/DSSM#2]
Original ticket: https://github.com/INWT/mpi-iso-app/issues/233

Batch export options for all different models mapping models with model parameters selected by user. The user would be able to select the different independent variables to be plotted and all outputs are saved under saved maps. The name string can be the variable name. The user can also download a zip file with all plots in a chosen format (same options as currently available). (2 days)

**Comment by arunge** [comment]
@isomemo I found this open task of the 20/21 contract. No new estimates had been done yet. I would try to implement this functionality within the restructuring task for the isomemo app: https://github.com/Pandora-IsoMemo/iso-app/issues/53 (E.)

That is, I will not make any additional estimates here. Would that be ok for you?

**Comment by arunge** [comment]
@isomemo With [version 24.05.6](https://github.com/Pandora-IsoMemo/DSSM/pull/223) on [DSSM beta](https://isomemoapp.com/app/iso-memo-app-beta) the feature to  download a zip file with all plots from selected saved maps in a chosen format was added. We can close here.

![image](https://github.com/Pandora-IsoMemo/DSSM/assets/16759098/7bb22a71-9808-4cdf-aca0-b30c6fcea984)
