### ISSUE TITLE
tclust option

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/DSSM#204]
To KernelR and KernelTimeR add tclust option (very similar to mclust but has additional outlier  parameter)

**Comment by arunge** [comment]
@f-lukas There is also this task for DSSM. Could you please check if you need more information here or if you could start working on this task?

**Comment by f-lukas** [comment]
@isomemo - I have one question regarding the input for the amount of clusters that are calculated. Can we use the same input field and values as for kmeans (see screenshot)? This would be the simplest solution. For mclust, we allow a range of clusters and then choose the optimal number with the BIC. For tclust the BIC is not provided and usually not used to choose the optimal number of clusters. Therefore I suggest to let the user define the amount of clusters as we do for kmeans. We would also add a note that the default value of 5 should be adjusted depending on the data.

![Bildschirmfoto vom 2024-08-09 11-11-52](https://github.com/user-attachments/assets/e9408abd-1e4f-423e-b0db-c6b125ac3ff2)

**Comment by arunge** [comment]
@f-lukas Today @isomemo confirmed that we can implement the same input as we use for `kmeans`. And please add the note (`helpText()`) that the default should be adjusted. Thanks!

**Comment by f-lukas** [comment]
@isomemo - tclust as clustering method is now available for testing in the beta app: https://pandoraapp.earth/app/dssm-beta

**Comment by isomemo** [comment]
@f-lukas  I loaded data via the option "Data networks" and then selected the network "IsoMemo-Humans". I included in my selection the fields for Location on which the clustering was applied.

tclust seemed to work but I got the following error message:

![image](https://github.com/user-attachments/assets/ac72ff78-133c-4ed5-b9be-e8e5478c9b5a)

**Comment by f-lukas** [comment]
@isomemo - This can happen if the restriction factor on the cluster covariance structure is too small. Currently the default restr.fact = 50 is used. We could add it as an input so that users can adjust this depending on the data.

> The constant restr.fact >= 1 constrains the allowed differences among group scatters. Larger values imply larger differences of group scatters. Setting restr.fact to 1, yields the strongest restriction, forcing all eigenvalues/determinants to be equal and so the method looks for similarly scattered (respectively spherical) clusters.

**Comment by arunge** [comment]
@f-lukas Please, add the new input and let us then discuss (in the respective PR) where to add a link to the docu of tclust.

**Comment by f-lukas** [comment]
The new input is now available in the beta app. Is there any more feedback? If not, I can close here.

**Comment by arunge** [comment]
@isomemo As mentioned today the new input "restriction factor" was added to [DSSM beta](https://isomemoapp.com/app/dssm-beta). You may test the clustering and let me know if you observe other issues.

I am closing here, feel free to re-open if needed.
