### ISSUE TITLE
Retirement of rgdal & rgeos: Problem with local development

### ISSUE THREAD

**Issue by jan-abel-inwt** [Pandora-IsoMemo/DSSM#228]
In the DSSM project, we currently use the `rgdal` and `rgeos` packages. However, both packages were retired at the end of 2023 as documented [here](https://github.com/Pandora-IsoMemo/drat/issues/22). These packages are no longer available on CRAN, which poses a challenge for local development.

We only utilize the `gecentroid()` function from the rgeos package. I propose replacing it with the `st_centroid()` function from the `sf` package, which is more modern and actively maintained. This change would help us reduce our dependency on outdated packages and streamline our development process.

https://gis.stackexchange.com/questions/43543/how-to-calculate-polygon-centroids-in-r-for-non-contiguous-shapes

**Comment by arunge** [comment]
@jan-abel-inwt Beta and main version are synchron again, so packages `rgdal` and `rgeos` were removed from both version. I am closing here. Feel free to re-open if something is missing.
