### ISSUE TITLE
Error: Argument is of Lenght zero.

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/DSSM#247]
For the attached model and dataset (sheet1), the attached error message is received in TimeR. 

[Model TimeR.zip](https://github.com/user-attachments/files/16840272/Model.TimeR.zip)
[SAAID Humans filtered.xlsx](https://github.com/user-attachments/files/16840275/SAAID.Humans.filtered.xlsx)
![Message error](https://github.com/user-attachments/assets/177aa439-61bd-4241-8d9f-7380782ccff1)

@arunge

**Comment by arunge** [comment]
I fixed the issue with [version 24.09.0](https://github.com/Pandora-IsoMemo/DSSM/pull/249) on [DSSM beta](https://isomemoapp.com/app/dssm-beta) which will be online soon.

Please, let me know if you find other issue, I am closing here.
