### ISSUE TITLE
AverageR: New (?) Error Message when using spherical Smooth Type and constant extrapolation with Bayesian Model

### ISSUE THREAD

**Issue by sarahdefant** [Pandora-IsoMemo/DSSM#251]
Hi. 
There seems to be a (potentially new?) issue when trying to run a Bayesian Model in AverageR in both the Main (24.8.1) and the Beta (24.9.1) versions when selecting spherical Smooth Type and constant extrapolation behaviour. 
The exact same selections with the exact same data worked fine a few months ago, but recently I have been getting this Error Message "Error in model fitting. Please check your input variables assignments and your data!". 

I am not getting this Error message when I just select "Spherical Smooth Type and constant extrapolation" or when I tick: Planar Smooth Type, constant extrapolation Bayesian Model. 
The combination of spherical, constant, and Bayesian does not work anymore (?), even though it did a few months ago with the same data. 
Is this a bug in the software or just an issue with my data/selection criteria?
Thanks (:

**Comment by arunge** [comment]
@mgross Please check the comment [here](https://github.com/Pandora-IsoMemo/DSSM/pull/253#discussion_r1776768690)!

**Comment by arunge** [comment]
@sarahdefant There seems to be an issue within the model calculation. I will let you know when a fix is online.
Thanks for reporting the issue and for your patience! :slightly_smiling_face:

**Comment by arunge** [comment]
@sarahdefant The issue should be fixed with [version 24.10.1](https://github.com/Pandora-IsoMemo/DSSM/pull/256) on both DSSM [main](https://isomemoapp.com/app/dssm) and [beta](https://isomemoapp.com/app/dssm-beta). I am closing here. Please, feel free to re-open if you have questions or other issues.
